### ISSUE TITLE
Результат выполнения функции не нужно сохранять в глобальной переменной

### ISSUE THREAD

**Issue by uzarsalan** [aldarsemenov/aldarsemenov#1]
У тебя в коде результат выполнения функции сохраняется в глобальной переменной, так делать не нужно. Верни необходимое значение внутри функции с помощью return и используй результат выполнения функции.

https://github.com/aldarsemenov/aldarsemenov/blob/7ef85afb305d83b793ccc020cf2ab7216d1168fe/hw16/script.js#L85

**Comment by aldarsemenov** [comment]
подправил посмотри верно же ?
