### ISSUE TITLE
Неверно назвал переменную index

### ISSUE THREAD

**Issue by uzarsalan** [aldarsemenov/aldarsemenov#2]
index называют переменную в которой хранится индекс элемента в массиве. В твоем случае лучше назвать переменную item (переводится как элемент) в этом и всех других местах

https://github.com/aldarsemenov/aldarsemenov/blob/7ef85afb305d83b793ccc020cf2ab7216d1168fe/hw16/script.js#L95

**Comment by aldarsemenov** [comment]
заменил
