### ISSUE TITLE
Некорректное название функции

### ISSUE THREAD

**Issue by uzarsalan** [aldarsemenov/aldarsemenov#3]
Старайся называть функцию так, чтобы было понятно что она делает и что возвращает. Когда функция называется veganOrNot (вегетарианская или нет), сложно понять что она должна вернуть в каком случае. Тут бы по логике подошло название типа checkNonVeganFood (проверка на невегетарианскость😅). Когда функция называется check(проверка), то скорее всего она возвращает true или false

https://github.com/aldarsemenov/aldarsemenov/blob/7ef85afb305d83b793ccc020cf2ab7216d1168fe/hw16/script.js#L86

**Comment by aldarsemenov** [comment]
исправил
