### ISSUE TITLE
vegan: Boolean - это надо убрать

### ISSUE THREAD

**Issue by uzarsalan** [aldarsemenov/aldarsemenov#4]
Уже разбирали на уроке что так писать нельзя
https://github.com/aldarsemenov/aldarsemenov/blob/7ef85afb305d83b793ccc020cf2ab7216d1168fe/hw16/script.js#L6

**Comment by aldarsemenov** [comment]
ага, забыл исправить в сделанной домашке. В json файле было исправлено) а тут как то забылось
